### ISSUE TITLE
Problems CIPS/NoC/DDR

### ISSUE THREAD

**Issue by ElMasto12** [Xilinx/XilinxCEDStore#234]
Hello, 

I try to communicate with the DDR through the CIPS and NoC. I have tested this example and I noticed something weird. At the line 153 here is this "Check data" :  
![image](https://user-images.githubusercontent.com/78360974/163404422-3a7e6d03-9b6b-45e9-8159-17a026cbc7b4.png)

Theorytically, DDR was wrote at those address before but with the two "read_burst" which are supposed to verify if datas are good are just comparing two vectors of zeros. I don't know why reading functions aren't working but in all my tests I just have some zeros everytime I want to read in the DDR whether it be with hte PMC_NOC_AXI, NOC_LPD_AXI or FPD_NOC_AXI. So I don't konw if writing functions don't work or reading fucntions or both. But a the end of this "check data" function there isn't any Error Message because the condition is that write_ddr_data isn't equal to read_ddr_data but there both are zeros.

![image](https://user-images.githubusercontent.com/78360974/163406434-d0813d23-e6b3-440c-b355-8ff70dc52578.png)

As you can see here, the "RDATA" value never change and stay at zeros.

Here are the writing commands which seems to work.

![image](https://user-images.githubusercontent.com/78360974/163407338-26c5a6f4-2369-4041-bfe3-d743cf27f25b.png)

and this is the code which describes those writings. 

![image](https://user-images.githubusercontent.com/78360974/163407472-96bcb8a4-9087-4c90-8c48-2f7d25f83d5b.png)

Someone can help me please ? I use Vivado 2021.2.1 and the part is xcvc1902-vsva2197-2MP-e-S

Thank you

**Comment by soltan74** [comment]
I have the same issue in example design and also in my own design. Read data from DDR is always zero in simulation. Does it known issue?
Thank you

**Comment by ElMasto12** [comment]
Hi,
I finally found the error, in the Block Design, open the Axi NoC and in the "DDR Basic" you have to check the box "Enabe Internal Responder" for the simulation. I don't know why they didn't check it for the design example.
