### ISSUE TITLE
no examples here

### ISSUE THREAD

**Issue by cederom** [Xilinx/XilinxCEDStore#99]
I am searching for Spartan7 Edge Accelerator Boad examples but no examples here at all.

Where can I find generic examples for Spartan7?

**Comment by lay-xilinx** [comment]
We will consider adding one for a future release.

**Comment by cederom** [comment]
Why only one? Isn't this repo a store of examples? How many examples are already here? Do I miss anything? :-)

**Comment by lay-xilinx** [comment]
Every design here can be downloaded and installed directly in the Vivado GUI.  You can download designs using Tools > XHUB Stores > Example Designs.  The only design we have today that supports the Spartan 7 board is the Microblaze Design Presets.  Once you download the example design, you can open it by creating a new project and choosing example design.  You will see the design that you downloaded and should be able to generate the design for the SP701. If you wish to contribute an example design, you can do so by creating all the files and submitting a pull request.
